### ISSUE TITLE
Stack top/bottom argument (uc-os-ii port)

### ISSUE THREAD

**Issue by vChavezB** [QuantumLeaps/qpcpp#12]
I was checking the source code for the uc-os ii port and found a possible bug.

In particular, when you create the task for the active object

https://github.com/QuantumLeaps/qpcpp/blob/8803d8faed8124deb91073e4cf8603fd9e0b07ba/ports/ucos-ii/qf_port.cpp#L111-L115

shouldn't there be as well a conditional compilation macro for the bottom part of the stack?

https://github.com/QuantumLeaps/qpcpp/blob/8803d8faed8124deb91073e4cf8603fd9e0b07ba/ports/ucos-ii/qf_port.cpp#L118

**Comment by quantum-leaps** [comment]
The issue is fixed in QP 7.0.0.
