### ISSUE TITLE
Zephyr module name

### ISSUE THREAD

**Issue by vChavezB** [QuantumLeaps/qpcpp#19]
I have been further working with zephyr modules and found out that by default the name of the module is its path. 

https://github.com/zephyrproject-rtos/zephyr/blob/e0fb04458f086111b95237bb6060f95738981fcd/cmake/modules/extensions.cmake#L391

In some cases if the project path is too large some warnings might appear. I would suggest to avoid this and have an easier way to access the module from cmake to change
[
`zephyr_library()
`](https://github.com/QuantumLeaps/qpcpp/blob/master/zephyr/CMakeLists.txt#L4)

to

`zephyr_library_named(qpcpp)`

More info about this cmake function

https://github.com/zephyrproject-rtos/zephyr/blob/e0fb04458f086111b95237bb6060f95738981fcd/cmake/modules/extensions.cmake#L418

Best regards
Victor

**Comment by quantum-leaps** [comment]
OK, the change has been made in `qpcpp/zephyr/CMakeLists.txt` and the file has been checked in. With that, I close this issue. Thanks a lot for the suggestion.
