### ISSUE TITLE
Two onStartup() callbacks in qk.cpp run()

### ISSUE THREAD

**Issue by dominic-valentino** [QuantumLeaps/qpcpp#20]
While stepping through the QK run, I noticed there were 2 `onStartup()` callbacks.
One on line 193 and another on line 204. The second is done with interrupts disabled.  

Was this on purpose?

**Comment by mattheweshleman** [comment]
code reference: https://github.com/QuantumLeaps/qpcpp/blob/5c7e0645b169f00e50077b34217ca5b68e7542ed/src/qk/qk.cpp#L193-L204

I don't see two calls in QV, for example:
https://github.com/QuantumLeaps/qpcpp/blob/5c7e0645b169f00e50077b34217ca5b68e7542ed/src/qv/qv.cpp#L113

**Comment by quantum-leaps** [comment]
Thank you for reporting. The repeated call to `onStartup()` in `qk.cpp` has been removed. The change has been already pushed to GitHub.
--MMS
