### ISSUE TITLE
 error: '_Noreturn' does not name a type 

### ISSUE THREAD

**Issue by vChavezB** [QuantumLeaps/qpcpp#21]
I have updated from tag v7.2.1 to the latest [commit ](https://github.com/QuantumLeaps/qpcpp/commit/5e83aa81bb4bc3c111a416d695889e258c1094fe)  and my zephyr project throws the compiling error

include/qassert.h:327:20: error: '_Noreturn' does not name a type
  327 | #define Q_NORETURN _Noreturn void

Is there something I have to be aware between version 7.2.1 and 7.2.2 for the Zephyr Port?

**Comment by quantum-leaps** [comment]
Thanks for reporting. The QP/C++ port to Zephyr has been updated and should work now. Please check out the latest version and try it out.
--MMS

**Comment by vChavezB** [comment]
I checked again and now it works
