### ISSUE TITLE
Missing (direct) documentation of QEVT_DYN_CTOR

### ISSUE THREAD

**Issue by maxmitti** [QuantumLeaps/qpcpp#23]
I discovered `QEVT_DYN_CTOR` by looking at the definition of `Q_NEW` in the `qp.hpp` header.
It was really difficult for me to discover that it is explained in the documentation of `Q_NEW`.
I think at least a reference to `Q_NEW` in the documentation of `QEVT_DYN_CTOR` would be helpful.

PS: The links to the `html` folder in the `README.md` don’t work when viewing on GitHub. I have seen that the folder is present in the release download.
A hint about that would also be nice.

**Comment by quantum-leaps** [comment]
Good point. The documentation of dynamic event management will be improved and extended.
--MMS

**Comment by quantum-leaps** [comment]
The design of the automatic event instance initialization during dynamic allocation has been redesigned in QP/C++ 8.0.0. The macro `QEVT_DYN_CTOR` has been replaced with `QEVT_PAR_INIT`, which is documented. With this comment, the issue is thus closed.
