### ISSUE TITLE
Broken link in example README

### ISSUE THREAD

**Issue by gzzi** [QuantumLeaps/qpcpp#24]
There is broken link in:

 - [blinky_ek-tm4c123gxl](
https://github.com/QuantumLeaps/qpcpp/blob/ae33ce613e18cfad6619afee5cbb130b74e29b12/examples/arm-cm/blinky_ek-tm4c123gxl/README.md)
 - [blinky_nucleo-c031c6](https://github.com/QuantumLeaps/qpcpp/blob/ae33ce613e18cfad6619afee5cbb130b74e29b12/examples/arm-cm/blinky_nucleo-c031c6/README.md) also note that the link seem to point to a `ek-tm4c123` page instead of nucleo...

(I didn't try the following)

**Comment by quantum-leaps** [comment]
Fixed.
