### ISSUE TITLE
CMake updates to address changes in QP/C++ V8.0.0

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/qpcpp#27]
- `cmakeSupport.md` updated
- `ports/CMakeLists.txt` updated to address mandatory inclusion of `qp_config.hpp`
- `src/qs/CMakeLists.txt` updated to address new license definitions

[qpcpp.diff.zip](https://github.com/user-attachments/files/17568526/qpcpp.diff.zip)

**Comment by quantum-leaps** [comment]
Merged and pushed into the qpcpp repo.
Thank you,
--MMS
