### ISSUE TITLE
Error on Line 169 include/qep.hpp

### ISSUE THREAD

**Issue by wallarug** [QuantumLeaps/qpcpp#4]
There is an error on Line 169 of include/qep.hpp.  There is an extra bracket on the end of the line containing `refCtr_(0U))`.  

The line should read `refCtr_(0U)`

https://github.com/QuantumLeaps/qpcpp/blob/master/include/qep.hpp#L169

**include/qep.hpp**
```
#ifdef Q_EVT_CTOR // Provide the constructor for the QEvt class?

    //************************************************************************
    class QEvt {
    public:
        //! public constructor (dynamic event)
        QEvt(QSignal const s) noexcept
          : sig(s)
          // poolId_/refCtr_ intentionally uninitialized
        {}
        enum StaticEvt : std::uint8_t { STATIC_EVT };

        //! public constructor (static event)
        QEvt(QSignal const s, StaticEvt /*dummy*/) noexcept
          : sig(s),
            poolId_(0U),
            refCtr_(0U))
        {}
```

Just thought someone should know.

**Comment by quantum-leaps** [comment]
Thanks for reporting. The bug will be fixed in the next QP/C++ release.
Also, there are some issues with QP/C++ port and examples for Qt, which will be fixed as well.
--MMS

**Comment by wallarug** [comment]
Thanks!
