### ISSUE TITLE
No Windows QActive::stop() implementation causes compiliation failure

### ISSUE THREAD

**Issue by DanielLyubin** [QuantumLeaps/qpcpp#5]
I develop both on embedded target and windows, and have same app-level code for both. I have code that must utilize the stop mechanism. It works on target since the port file has implementation, but doesn't compile on windows.

**Comment by quantum-leaps** [comment]
The QActive::stop() implementation will be added to all workstation QP/C/C++ ports (Win32 and POSIX) in the next official release.
--MMS
