### ISSUE TITLE
QF::newRef_ Should Support Static Events (Non-dynamic Events)

### ISSUE THREAD

**Issue by DanielLyubin** [QuantumLeaps/qpcpp#7]
Currently this function allows only dynamic events to add a new reference and increment the reference count. This is problematic because we have a use case where there are two possible sources for the same event - one sends a static event and one sends a dynamic one. The target AO needs to save the event pointer to use the event forever. The source is determined during run time. Current implementation forces *me* to check if the event is dynamic or not, instead of the function. 

A suitable solution would be checking if the event is dynamic. If it is, increment the ref. count. Otherwise, do nothing.

**Comment by quantum-leaps** [comment]
The [Q_NEW_REF()](https://www.state-machine.com/qpcpp/qf_8hpp.html#a10162978b156ab5d2fd2e3a7aa744ac0) API is an advanced optimization, which is intended to be used only for frequent _dynamic_ events, where such optimization is actually worth it. In all other cases, any information from an event that is needed beyond the current RTC step should be simply **copied** into the private data of the AO.

The QF::newRef_(), which underlines the Q_NEW_REF() macro, already asserts that the event is dynamic. This is exactly per the intent.

--MMS

**Comment by DanielLyubin** [comment]
I understand why it's needed. I'm saying that it needs to support non-dynamic events., i.e remove the assert

**Comment by quantum-leaps** [comment]
I'm not sure if removing the assert is a good idea. Without the asset the "event-reference" mechanism could be abused for static events.
